apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dkp-insights
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: dkp-insights
      sourceRef:
        kind: HelmRepository
        name: mesosphere.github.io-dkp-insights-charts-attached
        namespace: ${workspaceNamespace}
      version: v0.1.7
  interval: 15s
  install:
    remediation:
      retries: 30
  upgrade:
    remediation:
      retries: 30
  valuesFrom:
    - kind: ConfigMap
      name: dkp-insights-0.1.7-d2iq-defaults
  releaseName: dkp-insights
  targetNamespace: ${releaseNamespace}
