---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkp-insights-0.1.2-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    image:
      registry: "docker.io"
      repository: "mesosphere/insights"
      tag: "v0.1.2"
      imagePullPolicy: "IfNotPresent"
    backend:
       log_level: "INFO"
    cleanup:
      schedule: "@every 37m"
      logLevel: "DEBUG"
      insightsTTL: "168h"
      eventsTTL: "168h"
      alertsTTL: "168h"
      rejectedAlertsTTL: "168h"
