---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkp-insights-0.1.7-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    image:
      registry: "docker.io"
      repository: "mesosphere/insights"
      tag: "v0.1.7"
      imagePullPolicy: "IfNotPresent"
    backend:
      log_level: "INFO"
      resources:
        limits:
          cpu: "1000m"
          memory: "512Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"
    cleanup:
      schedule: "@every 37m"
      logLevel: "INFO"
      insightsTTL: "168h"
      eventsTTL: "168h"
      alertsTTL: "168h"
      rejectedAlertsTTL: "168h"
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
    initdb:
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
    reforwarder:
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
    resolutionCM:
      resources:
        limits:
          cpu: "250m"
          memory: "128Mi"
        requests:
          cpu: "100m"
          memory: "64Mi"
