name: Continuous Integration
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - km/TC_builds_into_gha

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Configure git for private repo access
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pre-commit Checks
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="env SKIP=no-commit-to-branch make pre-commit"

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Configure git for private repo access
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Unit Tests
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make test"

  build-image-bundle:
    name: Build Image Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Configure git for private repo access
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image Bundle
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.save-images.tar"

  push-ci-docker-image:
    name: Push CI Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Configure git for private repo access
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_READ_WRITE_USERNAME }}
          password: ${{ secrets.DOCKER_READ_WRITE_PASSWORD }}

      - name: Push Image
        run: make ci.docker.run RUN_WHAT="make ci.docker.push"
