name: Continuous Integration
on:
  workflow_dispatch:
  push:
    branches:
      - km/TC_builds_into_gha

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: 
    - self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Configure git for private repo access
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_READ_WRITE_USERNAME }}
          password: ${{ secrets.DOCKER_READ_WRITE_PASSWORD }}
      
      - name: Clean up Docker
        run: |
          docker ps -q | xargs -r docker stop
          docker system prune -a -f

      - name: Pre-commit Checks
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="env SKIP=no-commit-to-branch make pre-commit"

  unit-test:
    name: Unit Tests
    runs-on: 
    - self-hosted
    steps:
      - name: Run Unit Tests
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="env SKIP=no-commit-to-branch make pre-commit"

  build-image-bundle:
    name: Build Image Bundle
    runs-on: 
    - self-hosted
    steps:
      - name: Build Image Bundle
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.save-images.tar"

  push-ci-docker-image:
    name: Push CI Docker Image
    runs-on: 
    - self-hosted
    steps:
      - name: Clean up Docker
        run: |
          docker ps -q | xargs -r docker stop
          docker system prune -a -f

      - name: Push Image
        run: make ci.docker.run RUN_WHAT="make ci.docker.push"
