name: Continuous Integration
on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
      # - name: Set Env Variable
      #   run: |
      #     echo "CHECKOUT_BRANCH=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${GITHUB_HEAD_REF}
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Pre-commit Checks
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="env SKIP=no-commit-to-branch make pre-commit"

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Run Unit Tests
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make test"

  build-image-bundle:
    name: Build Image Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Build Image Bundle
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.save-images.tar"

  push-ci-docker-image:
    name: Push CI Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Push Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_READ_WRITE_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_READ_WRITE_PASSWORD }}
        run: make ci.docker.run RUN_WHAT="make ci.docker.push"
