name: Debug Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        type: string
        required: true
        default: '0'
  pull_request:

jobs:
  release:
    name: Debug Release
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Set Env Variables
        run: |
          current_tag=${GITHUB_REF#refs/tags/}
          current_branch=${{ inputs.tag }}
          set +e
          PRERELEASE_BUILDMETADATA=$(echo ${current_branch} | perl -ne 'print "$4$5" if /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/')
          set -e
          if [ ! -z ${PRERELEASE_BUILDMETADATA} ]
          then
            checkout_branch=beta
          else
            checkout_branch=main
          fi
          echo "PRERELEASE_BUILDMETADATA=$PRERELEASE_BUILDMETADATA" >> $GITHUB_ENV
          echo "CURRENT_TAG=$current_tag" >> $GITHUB_ENV
          echo "BUILD_BRANCH=$current_branch" >> $GITHUB_ENV
          echo "CHECKOUT_BRANCH=$checkout_branch" >> $GITHUB_ENV

      - name: Echo Env
        run: |
          echo "PRERELEASE_BUILDMETADATA=${{ env.PRERELEASE_BUILDMETADATA }} CATALOG_APPLICATIONS_VERSION=${{ env.BUILD_BRANCH }} INSIGHTS_CATALOG_APPLICATIONS_REF=${{ env.CHECKOUT_BRANCH }} CURRENT_TAG=${{ env.CURRENT_TAG }}"
