name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - km/TC_builds_into_gha

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: test step
        run: |
          current_branch=${GITHUB_REF#refs/heads/}
          echo ${current_branch}
          IS_BETA=$(echo ${current_branch} | grep '^v[0-9]\.[0-9]\.[0-9]-beta.*$')
          if [ ! -z $IS_BETA ]
          then
            CHECKOUT_BRANCH=beta
          else
            CHECKOUT_BRANCH=main
          fi
          echo ${CHECKOUT_BRANCH}

      # - name: Checkout code
      #   uses: actions/checkout@v3
      #   with:
      #     ref: beta # TODO: select branch based on current branch
      #     token: ${{ secrets.MERGEBOT_TOKEN }}

      # - name: Configure git for private repo access
      #   if: ${{ github.actor != 'dependabot[bot]' }}
      #   run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      # - name: Install AWS cli
      #   uses: unfor19/install-aws-cli-action@v1.0.3
      #   with:
      #     arch: amd64

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::633059600857:role/insights-catalog-applications
      #     aws-region: us-west-2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Release Repo Archive
      #   run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.repo-archive CATALOG_APPLICATIONS_VERSION=%teamcity.build.branch% INSIGHTS_CATALOG_APPLICATIONS_REF=${CHECKOUT_BRANCH}"

      # - name: Release Charts Bundle
      #   run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.charts-bundle INSIGHTS_CATALOG_APPLICATIONS_REF=${CHECKOUT_BRANCH}"

      # - name: Release Save Images
      #   run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.save-images.tar INSIGHTS_CATALOG_APPLICATIONS_REF=${CHECKOUT_BRANCH}"

      # - name: Release S3
      #   run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make release.s3 CATALOG_APPLICATIONS_VERSION=%teamcity.build.branch% INSIGHTS_CATALOG_APPLICATIONS_REF=${CHECKOUT_BRANCH}"
