name: Sync Branches with Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.MERGEBOT_TOKEN}}

jobs:
  sync-beta-with-main:
    runs-on: ubuntu-latest
    name: Sync Beta branch with Main
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}
          fetch-depth: 0

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_config_global: true

      - name: Opening pull request in Beta branch
        id: pull
        run: |
          git checkout main
          hub pull-request -m "chore: Sync main with beta" \
            -m "Sync latest main with beta branch" \
            -b beta \
            -l "ok-to-test","ready for review"
        # uses: tretuna/sync-branches@1.2.0
        # with:
        #   GITHUB_TOKEN: ${{ secrets.MERGEBOT_TOKEN }}
        #   FROM_BRANCH: 'main'
        #   TO_BRANCH: 'beta'
