name: Sync Branches with Main

on:
  push:
    branches:
      - main-gha-test

jobs:
  sync-beta-with-main:
    runs-on: ubuntu-latest
    name: Sync Beta branch with Main
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_config_global: true

      - name: Opening pull request in Beta branch
        id: pull
        uses: tretuna/sync-branches@1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          FROM_BRANCH: 'main-gha-test'
          TO_BRANCH: 'beta-gha-test'
