name: Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - km/TC_builds_into_gha

jobs:
  release:
    name: Unit Tests
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      id-token: write
      issues: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: 
    - self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MERGEBOT_TOKEN }}

      - name: Configure git for private repo access
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: git config --global url.https://${{ secrets.MERGEBOT_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_READ_WRITE_USERNAME }}
          password: ${{ secrets.DOCKER_READ_WRITE_PASSWORD }}

      - name: Run Unit Tests
        run: make ci.docker.run GOOS=linux GOARCH=amd64 RUN_WHAT="make test"

      - name: Clean up Docker
        run: |
          docker ps -q | xargs -r docker stop
          docker system prune -a -f
